config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'beachs#index'
  resources :beachs do
    collection do
      get 'search'
    end
  end
  get 'beach/search', to: 'beachs#search_index'
end

app/models/activity.rb
class Activity < ActiveHash::Base
  self.data = [
    {id: 0, name: '海水浴'},
    {id: 1, name: 'シュノーケリング'},
    {id: 2, name: 'SUP'},
    {id: 3, name: 'サーフィン'},
    {id: 4, name: 'BBQ/焚き火'}
  ]
  
  include ActiveHash::Associations
  has_many :beach_activitys

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  

end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 0, name: '北部'},
    { id: 1, name: '中部'},
    { id: 2, name: '南部'}
  ]

  include ActiveHash::Associations
  has_many :beachs

end

app/models/beach.rb
class Beach < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area
  belongs_to :activity
  belongs_to :facility

  belongs_to :user
end
class Beach < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to_active_hash :area
  has_many :beach_activitys, dependent: :destroy
  has_many :beach_facilitys, dependent: :destroy
  belongs_to_active_hash :activity, through: :beach_activitys
  belongs_to_active_hash :facility, through: :beach_facilitiys

  belongs_to :user
  has_one_attached :image, dependent: :destroy

end

app/models/beach_activity.rb
class BeachActivity < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :beach
  belongs_to :user
  
  belongs_to_active_hash :activity
end

app/models/beach_facility.rb
class BeachFacility < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :beach
  belongs_to :user
  
  belongs_to_active_hash :facility
end

app/models/beach_formobject.rb
class BeachFormobject
  include ActiveModel::Model
  include ActiveModel::Attributes

  attr_accessor :user_id, :name, :detail, :area_id, :image, 
                :beach_id, :activity_id, :facility_id, :activitys, :facilitys

  with_options presence: true do
    validates :name
    validates :detail
    validates :area_id
    validates :activity_id
    validates :facility_id
    validates :image
  end


  def initialize(attributes = nil, beach: Beach.new )
    @beach = beach
    attributes ||= default_attributes
    super(attributes)
  end

  def save
    raturn false if invalid?

    ActiveRecord::Base.transaction do
      beach = Beach.create(name: name, detail: detail, area_id: area_id, image: image, user_id: user_id)

      activity_id.each do |activity|
        BeachActivity.create(beach_id: beach.id, activity_id: activity, user_id: user_id)
      end
  
      facility_id.each do |facility|
        BeachFacility.create(beach_id: beach.id, facility_id: facility, user_id: user_id)
      end
    end

    true
  end

  def update
    raturn false if invalid?
    ActiveRecord::Base.transaction do
      BeachActivity.where(beach_id: @beach.id).delete_all
      activity_id.each do |activity|
        activityIDs = BeachActivity.where(beach_id: @beach.id, user_id: user_id, activity_id: activity).first_or_initialize if activity.present?
        activityIDs.save if activity.present?
      end

      BeachFacility.where(beach_id: @beach.id).delete_all
      facility_id.each do |facility|
        facilityIDs = BeachFacility.where(beach_id: @beach.id, user_id: user_id, facility_id: facility).first_or_initialize if facility.present?
        facilityIDs.save if facility.present?
      end

      @beach.update!(name: name, detail: detail, area_id: area_id, image: image, user_id: user_id)
    end

    true
  end

  private

  def default_attributes
    {
      name: @beach.name,
      detail: @beach.detail,
      area_id: @beach.area_id,
      image: @beach.image,
      user_id: @beach.user_id,
      activity_id: @beach.beach_activitys.pluck(:activity_id),
      facility_id: @beach.beach_facilitys.pluck(:facility_id)
    }
  end
end

app/models/facility.rb
class Facility < ActiveHash::Base
  self.data = [
    {id: 0, name: 'ライフセーバー'},
    {id: 1, name: '防護ネット'},
    {id: 2, name: '売店'},
    {id: 3, name: 'シャワー'},
    {id: 4, name: '駐車場'},
    {id: 5, name: 'トイレ'}
  ]

  include ActiveHash::Associations
  has_many :beach_facilitiys
  has_many :beachs, through: :beach_facilitiys

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :beachs
  has_many :beach_activitys
  has_many :beach_facilitys

  validates :nickname, presence: true

  validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i,
                      message: 'is invalid. Input a mixture of single-byte alphanumeric characters.'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :atuhenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/beachs_controller.rb
class BeachsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search_index]
  before_action :find_beach, only: [:show, :destroy, :edit, :update]
  before_action :user_signed?, only: [:index, :search_index, :new, :create, :show, :edit, :update, :destroy]
  before_action :ensure_user_admin, only: [:new, :destroy, :edit]

  def index
  end

  def search_index
    if params[:q]&.dig(:name)
      squished_keywords = params[:q][:name].squish
      params[:q][:name_cont_any] = squished_keywords.split(" ")
    end
    @q = Beach.ransack(params[:q])
    @beach = @q.result.includes(:beach_activitys, :beach_facilitys)
  end

  def search
    return nil if params[:keyword] == ""
    beach = Beach.where(['name LIKE ?', "%#{params[:keyword]}%"] )
    render json:{ keyword: beach }
  end

  def new
    @beach_formobject = BeachFormobject.new
  end

  def create 
    @beach_formobject = BeachFormobject.new(beach_formobject_params)
    if @beach_formobject.valid?
      @beach_formobject.save
      redirect_to beach_search_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    @beach_formobject = BeachFormobject.new(beach: @beach)
  end

  def update
    @beach_formobject = BeachFormobject.new(beach_formobject_params, beach: @beach)
    @beach_formobject.image ||= @beach.image.blob

    if @beach_formobject.valid?
      @beach_formobject.update
      redirect_to beach_search_path
    else
      render :edit
    end
  end

  def destroy
    @beach.destroy
    redirect_to beach_search_path
  end

  private

  def beach_formobject_params
    params.require(:beach_formobject).permit(
      :name, :detail, :area_id, :image, activity_id: [], facility_id: []).merge(
        user_id: current_user.id
      )
  end

  def user_signed?
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end

  def find_beach
    @beach = Beach.find(params[:id])
  end

  def ensure_user_admin
    redirect_to beach_search_path if @user.admin == false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beach_helper.rb
module BeachHelper
end

app/views/beach/search_index.html.erb
<div class="wrapper">
  <%= render "header" %>
  <div class="search_top">
    <%= form_with(url: beach_search_path, local: true, method: :get, class: "search_form") do |form| %>
      <%= form.text_field :keyword, placeholder: "キーワード、ビーチ名で検索する", class: "search_input" %>
      <%= form.submit "検索", class: "search_btn" %>
    <% end %>
  </div>
  <div class="side_bar">
    <div class="side_bar_head">
      <p>アクティビティ</p>
      <div class="activity">
        <div class="activity_one">
          <input type="checkbox" id="sea_bathing" name="sea_bathing" class="check_box">
          <label for="sea_bathing" class="label_name seabath" >海水浴</label>
        </div>
        <div class="activity_two">
          <input type="checkbox" id="snorkeling" name="snorkeling" class="check_box">
          <label for="snorkeling" class="label_name snorkrel">シュノーケリング</label>
        </div>
        <div class="activity_three">
          <input type="checkbox" id="sup" name="sup" class="check_box">
          <label for="sup" class="label_name stand">SUP</label>
        </div>
        <div class="activity_four">
          <input type="checkbox" id="surfing" name="surfing" class="check_box">
          <label for="surfing" class="label_name surf">サーフィン</label>
        </div>
        <div class="activity_five">
          <input type="checkbox" id="bbq_bonfire" name="bbq_bonfire" class="check_box">
          <label for="bbq_bonfire" class="label_name bbq">BBQ/焚き火</label>
        </div>
      </div>
    </div>  
    <div class="side_bar_middle">
      <p>設備</p>
      <div class="facility">
        <div class="facility_one">
          <input type="checkbox" id="life_saver" name="life_saver" class="check_box">
          <label for="life_saver" class="label_name saver" >ライフセーバー</label>
        </div>
        <div class="facility_two">
          <input type="checkbox" id="protection_net" name="protection_net" class="check_box">
          <label for="protection_net" class="label_name net">防護ネット</label>
        </div>
        <div class="facility_three">
          <input type="checkbox" id="store" name="store" class="check_box">
          <label for="store" class="label_name shop">売店</label>
        </div>
        <div class="facility_four">
          <input type="checkbox" id="shower" name="shower" class="check_box">
          <label for="shower" class="label_name sho">シャワー</label>
        </div>
        <div class="facility_five">
          <input type="checkbox" id="parking" name="parking" class="check_box">
          <label for="parking" class="label_name park">駐車場</label>
        </div>
        <div class="facility_six">
          <input type="checkbox" id="toilet" name="toilet" class="check_box">
          <label for="toilet" class="label_name kawaya">トイレ</label>
        </div>
    </div>  
  </div>
</div>

app/views/beachs/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error_alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error_message"><%= message %>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/beachs/_header.html.erb
<div class="header" >
  <div class="site_title">
    <%= link_to 'Beach', root_path, class: "logo" %>
  </div>
  <div class="nav">
    <ul>
      <li><%= link_to 'Search', beach_search_path, class: "search" %></li>
    <% if user_signed_in?%> 
      <li><%= link_to 'Signout', destroy_user_session_path, method: :delete, class: "logout"%></li>

      <% if user.admin == true %>
        <li><%= link_to "New", new_beach_path, class: "new" %></li>
      <% end %>

    <% else %>
      <li><%= link_to 'Signup', new_user_registration_path, class: "signup" %></li>
      <li><%= link_to 'Signin', new_user_session_path, class: "signin" %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/beachs/edit.html.erb
<div class="beach_register">
  <%= render "header", user: @user %>
  <div class="beach_register_main">
    <div class="beach_register_box">
      <h2 class="beach_register_title">Beach Information Edit</h2>
      <%= form_with(model: @beach_formobject, url: beach_path, method: :patch ,local: true) do |f| %>
      <div class="beach_info_base">
        <%= render "layouts/error_messages", model: f.object %>
        <div class="beach_info_title base">
          Basic information
        </div>
        <%# ビーチ名 %>
        <div class="form_box name">
          <div class="item_title">
            Name
          </div>
          <div class="item_input">
            <%= f.text_area :name, class:"items_text", id:"item_name", maxlength:"40" %>
          </div>
        </div>
        <%# /ビーチ名 %>
        <%# ビーチ画像 %>
        <div class="form_box image">
          <div class="item_title">
            Photo
          </div>
          <div class="item_input">
            <%= f.file_field :image, id:"item_image" %>
          </div>
        </div>
        <%# /ビーチ画像 %>
        <%# ビーチ説明 %>
        <div class="form_box name">
          <div class="item_title">
            Detail
          </div>
          <div class="item_input">
            <%= f.text_area :detail, class:"items_text", id:"item_info", maxlength:"1000" %>
          </div>
        </div>
        <%# /ビーチ説明 %>
        <%# 地域 %>
        <div class="form_box name">
          <div class="item_title">
            Area
          </div>
          <div class="item_input">
            <%= f.collection_select :area_id, Area.all, :id, :name, {include_hidden: false}, {class: "select_box", id:"area"} %>
          </div>
        </div>
        <%# /地域 %>
      </div>
      <div class="beach_info activity">
        <div class="beach_info_title activity">
          Activity
        </div>
        <%# アクティビティ %>
        <div class="form_box activity">
          <div class="item_input check_box">
            <%= f.collection_check_boxes :activity_id, Activity.all, :id, :name, { checked: @beach_formobject.activity_id, include_hidden: false}, {class: 'check_box', id:'activity'} %>
          </div>
        </div>
        <%# /アクティビティ %>
      </div>
      <div class="beach_info facility">
        <div class="beach_info_title activity">
          Facility
        </div>
        <%# 設備 %>
        <div class="form_box facility ">
          <div class="item_input check_box">
            <%= f.collection_check_boxes :facility_id, Facility.all, :id, :name,{ checked: @beach_formobject.facility_id, include_hidden: false}, {class:"check_box", id:"facility"} %>
          </div>
        </div>
        <%# /設備 %>
      </div>
      <%# 下部ボタン %>
      <div class="btn_contents">
        <%= f.submit "Edit" ,class:"register_btn" %>
      </div>
      <%# /下部ボタン %>
      <% end %>
    </div>
  </div>
</div>

app/views/beachs/new.html.erb
<div class="beach_register">
  <%= render "header", user: @user %>
  <div class="beach_register_main">
    <div class="beach_register_box">
      <h2 class="beach_register_title">Beach Information Input</h2>
      <%= form_with model: @beach_formobject, url: beachs_path, local: true do |f| %>
      <div class="beach_info_base">
        <%= render "layouts/error_messages", model: f.object %>
        <div class="beach_info_title base">
          Basic information
        </div>
        <%# ビーチ名 %>
        <div class="form_box name">
          <div class="item_title">
            Name
          </div>
          <div class="item_input">
            <%= f.text_area :name, class:"items_text", id:"item_name", maxlength:"40" %>
          </div>
        </div>
        <%# /ビーチ名 %>
        <%# ビーチ画像 %>
        <div class="form_box image">
          <div class="item_title">
            Photo
          </div>
          <div class="item_input">
            <%= f.file_field :image, id:"item_image" %>
          </div>
        </div>
        <%# /ビーチ画像 %>
        <%# ビーチ説明 %>
        <div class="form_box name">
          <div class="item_title">
            Detail
          </div>
          <div class="item_input">
            <%= f.text_area :detail, class:"items_text", id:"item_info", maxlength:"1000" %>
          </div>
        </div>
        <%# /ビーチ説明 %>
        <%# 地域 %>
        <div class="form_box name">
          <div class="item_title">
            Area
          </div>
          <div class="item_input">
            <%= f.collection_select :area_id, Area.all, :id, :name, {include_hidden: false}, {class: "select_box", id:"area"} %>
          </div>
        </div>
        <%# /地域 %>
      </div>
      <div class="beach_info activity">
        <div class="beach_info_title activity">
          Activity
        </div>
        <%# アクティビティ %>
        <div class="form_box activity">
          <div class="item_input check_box">
            <%= f.collection_check_boxes :activity_id, Activity.all, :id, :name, {include_hidden: false}, {class: 'check_box', id:'activity'} %>
          </div>
        </div>
        <%# /アクティビティ %>
      </div>
      <div class="beach_info facility">
        <div class="beach_info_title activity">
          Facility
        </div>
        <%# 設備 %>
        <div class="form_box facility ">
          <div class="item_input check_box">
            <%= f.collection_check_boxes :facility_id, Facility.all, :id, :name,  {include_hidden: false}, {class:"check_box", id:"facility"} %>
          </div>
        </div>
        <%# /設備 %>
      </div>
      <%# 下部ボタン %>
      <div class="btn_contents">
        <%= f.submit "Register" ,class:"register_btn" %>
      </div>
      <%# /下部ボタン %>
      <% end %>
    </div>
  </div>
</div>

app/views/beachs/search_index.html.erb
<div class="wrapper">
  <%= render "header", user: @user %>
  <%= search_form_for @q, url: beach_search_path, html: {id: "detailed_search_form", class: "searchs" } do |f| %>
  <div class="search_top">
    <div class="search_form">
      <%= f.text_field :name, placeholder: "キーワード、ビーチ名で検索する", value: params[:q]&.dig(:name), class: "search_input", id: "keyword" %>
      <%= f.submit "検索", class: "search_btn" %>
      <div id="search_result"></div>
    </div>
  </div>
  <div class="main">
    <div class="side_bar">
      <div class="side_bar_head">
        <p>アクティビティ</p>
        <div class="activitys">
          <%= f.collection_check_boxes(:beach_activitys_activity_id_in, Activity.all, :id, :name, {include_hidden: false}, {class: "checkbox", id:"activity_check"}) do |b| %>
            <div class="activity">
              <%= b.check_box + b.label { b.text }%>
            </div>
          <% end %>
        </div>
      </div>  
      <div class="side_bar_middle">
        <p>設備</p>
        <div class="facilitys">
          <%= f.collection_check_boxes(:beach_facilitys_facility_id_in, Facility.all, :id, :name, {include_hidden: false}, {class: "checkbox", id:"facility_check"}) do |b| %>
              <div class="facility">
                <%= b.check_box + b.label { b.text }%>
              </div>
            <% end %>
        </div>
      </div>  
      <%= f.submit '検索' %>
    </div>
    <div class="right_main">
      <% @beach.each do |beach| %>
        <%= link_to beach_path(beach.id) do %>
        <div id="beach_box">
          <%= image_tag beach.image, alt:"beach_sample.jpg" ,class:"beach_box_img" %><br>
          <h2 class="beach_name">
            <%= beach.name %>
          </h2>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/beachs/show.html.erb
<div class="wrapper">
  <%= render "header", user: @user %>
  <div class="beach-show">
    <div class="show_top">
      <%= image_tag @beach.image, alt:"beach_sample.jpg" ,class: "beach_box_show_img" %>
    </div>
    <div class="show_main">
      <div class="show_main_block">
        <div class="beach-info basic">
          <h3 class="info_title">ビーチ情報</h3>
          <div class="info_beach" id="info_name">
            <div class="beach_contein_title">ビーチ名</div>
            <div class="beach_contein">
              <%= @beach.name %>
            </div>
          </div>
          <div class="info_beach" id="info_detail">
            <div class="beach_contein_title">ビーチ詳細</div>
            <div class="beach_contein">
              <%= @beach.detail %>
            </div>
          </div>
          <div class="info_beach" id="info_area">
            <div class="beach_contein_title">ビーチエリア</div>
            <div class="beach_contein">
              <%= @beach.area.name %>
            </div>
          </div>
        </div>
        <div class="beach-info activity">
          <h3 class="info_title">アクティビティ</h3>
           <div class="info_beach_name">
            <% (@beach.beach_activitys).each do |activity| %>
              <p class="info_beach_activity">・<%= activity.activity.name %></p>
            <% end %>
          </div>
        <div class="beach-info facility">
          <h3 class="info_title">施設情報</h3>
          <div class="info_beach_name">
            <% (@beach.beach_facilitys).each do |facility| %>
              <p class="info_beach_facility">・<%= facility.facility.name %></p>
            <% end %>
          </div>
        </div>
      </div>
      <div id="invisible_links">
        <% if @user.admin == true %>
          <%= link_to "Edit", edit_beach_path(@beach), method: :get, class: "beach_edit_btn" %>
            <p class="or-text">or</p>
          <%= link_to "Delete", beach_path(@beach), method: :delete, class:"beach_destroy_btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beach</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'index' %>
    <link href="https://fonts.googleapis.com/earlyaccess/hannari.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>